import mysql from 'mysql2/promise';
import dotenv from 'dotenv';
dotenv.config();

const pool = mysql.createPool({
    host: process.env.DATABASE_HOST,
    user: process.env.DATABASE_USER,
    password: process.env.DATABASE_USER_PASSWORD,
    database: process.env.DATABASE_NAME,
    waitForConnections: true,
    connectionLimit: 20,
    multipleStatements: true,
});

export async function poolConn(): Promise<mysql.PoolConnection | null> {
    try {
        const poolConn = await pool.getConnection();
        return poolConn;
    } catch (error) {
        console.error('Error in @/database/conn.ts generated by func poolConn details: ', error)
        return null;
    }
}