import { timeStampGen } from '../utils/global-helpers';
import { poolConn } from './conn';
import { ResultSetHeader } from 'mysql2';
import { Project } from '../utils/types';

export async function updateProject(id: number, name: string, description: string, source:string, image:string, enabled: boolean, apiKey: string): Promise<boolean | Project> {
    const pool = await poolConn();
    if (!pool) {
        return false;
    }

    try {

        const [rows] = await pool.query<ResultSetHeader>('UPDATE projects SET name = ?, description = ?, github = ?, image = ?, enabled = ?, apiKey = ? WHERE id = ?', [name, description, source, image, enabled, apiKey, id]);
        if (rows.affectedRows <= 0) {
            return false;
        }

        const updatedProject = {
            id,
            name,
            description,
            github: source,
            image,
            enabled,
            apiKey
        }

        return updatedProject;
        
    } catch (error) {
        console.error(timeStampGen(), 'Error in @/database/data-create.ts generated by func updateProject details: ', error)
        return false;
    } finally {
        pool.release();
    };
}
