import { timeStampGen } from '../utils/global-helpers';
import { poolConn } from './conn';
import { ResultSetHeader } from 'mysql2';
import { Project } from '../utils/types';

export async function createProject(name: string, description: string, source:string, image:string): Promise<boolean | Project> {
    const pool = await poolConn();
    if (!pool) {
        return false;
    }

    try {
        const [rows] = await pool.query<ResultSetHeader>('INSERT INTO projects (name, description, github, image) VALUES (?, ?, ?, ?)', [name, description, source, image]);
        if (rows.affectedRows <= 0) {
            return false;
        }

        const newProject = {
            id: rows.insertId,
            name,
            description,
            github: source,
            image,
            enabled: true
        }

        return newProject;
    } catch (error) {
        console.error(timeStampGen(), 'Error in @/database/data-create.ts generated by func createProject details: ', error)
        return false;
    } finally {
        pool.release();
    };
}
