import { timeStampGen } from '../utils/global-helpers';
import { poolConn } from './conn';
import { PrLog, Project } from '../utils/types';
import { RowDataPacket } from 'mysql2';

export async function getProjects(): Promise<Project[] | [] | null> {
    const pool = await poolConn();
    if (!pool) {
        return null;
    }

    try {
        const [rows] = await pool.query<RowDataPacket[]>('SELECT id, name, description, github, image, enabled FROM projects ORDER BY updated_at DESC');
        if (rows.length <= 0) {
           return [];
        }

        const projects: Project[] = [];
        for (const row of rows) {
            projects.push({
                id: row.id,
                name: row.name,
                description: row.description,
                github: row.github,
                enabled: !!row.enabled,
                image: row.image
            });
        }

        return projects;
    } catch (error) {
        console.error(timeStampGen(), 'Error in @/database/data-get.ts generated by func getProjects details: ', error)
        return null;
    } finally {
        pool.release();
    };
};

export async function getProject(id: number): Promise<Project | null> {
    const pool = await poolConn();
    if (!pool) {
        return null;
    }

    try {
        const [rows] = await pool.query<RowDataPacket[]>('SELECT id, name, description, github, image, enabled, apiKey, updated_at FROM projects WHERE id = ? LIMIT 1', [id]);
        if (rows.length <= 0) {
            return null;
        }

        const row = rows[0];
        return {
            id: row.id,
            name: row.name,
            description: row.description,
            github: row.github,
            image: row.image,
            enabled: !!row.enabled,
            apiKey: row.apiKey,
            // convert the date to a format dd.mm.yyyy at hh:mm:ss
            updated_at: new Date(row.updated_at).toLocaleString('bg-BG', { timeZone: 'Europe/Sofia' })
        };
    } catch (error) {
        console.error(timeStampGen(), 'Error in @/database/data-get.ts generated by func getProject details: ', error)
        return null;
    } finally {
        pool.release();
    };
};

export async function getProjectLogs(id: number): Promise<PrLog | null> {
    const pool = await poolConn();
    if (!pool) {
        return null;
    }

    try {
        // check if the id exists in the database
        const [check] = await pool.query<RowDataPacket[]>('SELECT name FROM projects WHERE id = ? LIMIT 1', [id]);
        if (check.length <= 0) {
            return null;
        }

        const [rows] = await pool.query<RowDataPacket[]>('SELECT * FROM errors WHERE project_id = ? ORDER BY timestamp DESC LIMIT 30', [id]);
        if (rows.length <= 0) {
            return {
                logs: [],
                projectName: check[0].name
            }
        }
        console.log(rows)
        const logs: PrLog['logs'] = [];
        for (const row of rows) {
            logs.push({
                id: row.id,
                project_id: row.project_id,
                type: row.type,
                code: row.code,
                message: row.message,
                timestamp: new Date(row.timestamp).toLocaleString('bg-BG', { timeZone: 'Europe/Sofia' }),
                location: row.location
            });
        }

        return {
            logs: logs,
            projectName: check[0].name
        };
    } catch (error) {
        console.error(timeStampGen(), 'Error in @/database/data-get.ts generated by func getProjectLogs details: ', error)
        return null;
    } finally {
        pool.release();
    };
}