import { timeStampGen } from '../utils/global-helpers';
import { poolConn } from './conn';
import { ResultSetHeader } from 'mysql2';

export async function deleteProject(id: number): Promise<boolean> {
    const pool = await poolConn();
    if (!pool) {
        return false;
    }

    try {
        const [rows] = await pool.query<ResultSetHeader>('DELETE FROM projects WHERE id = ?', [id]);
        if (rows.affectedRows <= 0) {
            return false;
        }

        return true;
    } catch (error) {
        console.error(timeStampGen(), 'Error in @/database/data-create.ts generated by func deleteProject details: ', error)
        return false;
    } finally {
        pool.release();
    };
}
